# spotify-player configuration
# Docs: https://github.com/aome510/spotify-player/blob/master/docs/config.md

client_id = "e0dfdfe54e7d418f90f8d93c5283dad8"

theme = "default"
playback_format = "{track} • {artists}"
copy_command = { command = "pbcopy", args = [] }
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = ""
pause_icon = ""
liked_icon = "♥"
border_type = "Rounded"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
playback_window_width = 6
enable_media_control = false
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = true
default_device = "spotifyd"

[device]
name = "spotify-player"
device_type = "computer"
volume = 70
bitrate = 320
audio_cache = true
normalization = false
